"""Data & Methodology — How should this dashboard be interpreted?"""
from __future__ import annotations

import streamlit as st

from components.headers import page_header, section_header


def render(is_demo, data_path, hourly_path, mta_path):
    page_header(
        "Data & Methodology",
        "How should this dashboard be interpreted?",
        badge="Historical",
    )

    # ── How to read ──
    section_header("How to read this dashboard")

    with st.expander("Benchmark role", expanded=True):
        st.markdown(
            "Bay Wheels appears only in the high-level comparison. "
            "Forecasting, station rankings, and funding recommendations are NYC-only."
        )

    with st.expander("Demand pressure"):
        st.markdown(
            "Average daily trips divided by current dock capacity. "
            "It is a prioritization signal, not proof that a station should be expanded."
        )

    with st.expander("Demand forecast"):
        st.markdown(
            "XGBoost model trained on 21 features including weather deviations, "
            "MTA transit data, and temporal lag features. The interactive scenario "
            "view provides planning estimates — replace with agency-validated numbers "
            "before real funding decisions."
        )

    with st.expander("MTA connection"):
        st.markdown(
            "Compares transit demand and reliability with bike demand "
            "to identify potential first/last-mile and disruption-resilience gaps. "
            "It is a prioritization signal, not causation."
        )

    with st.expander("Investment strategy"):
        st.markdown(
            "Ranks expansions by public NPV, benefit-cost ratio, new trips, "
            "operating support, and fiscal sustainability. Inputs are assumptions "
            "and should be replaced with agency-validated capital, operating, "
            "revenue, equity, and benefit estimates before a real funding decision."
        )

    with st.expander("Scope"):
        st.markdown(
            "Bay Wheels serves the wider Bay Area. Its benchmark is labeled "
            "separately and does not enter NYC funding recommendations."
        )

    with st.expander("Peak demand heatmap"):
        st.markdown(
            "Hour-of-day × day-of-week trip counts, NYC only. "
            "Built from a separate hourly aggregation since the daily dataset "
            "drops timestamps down to the day. It reflects its own hourly sample "
            "period rather than the sidebar date range."
        )

    # ── Data pipeline ──
    st.markdown('<hr class="section-divider">', unsafe_allow_html=True)
    section_header("Data pipeline")

    st.markdown("**Expected datasets**")
    st.code(
        "data/processed/bike_share_daily.parquet\n\n"
        "date | city | system | station_name | lat | lon | rider_type |\n"
        "trips | electric_trips | capacity",
        language="text",
    )
    st.code(
        "data/processed/mta_bike_opportunity.parquet\n\n"
        "station_name | neighborhood | mta_daily_riders | mta_delay_rate",
        language="text",
    )
    st.code(
        "data/processed/bike_share_hourly.parquet\n\n"
        "date | hour | day_name | city | system | rider_type |\n"
        "trips | electric_trips",
        language="text",
    )

    st.caption(
        f"Current source: {'built-in demonstration dataset' if is_demo else data_path}"
    )

    # ── Data-type badges ──
    st.markdown('<hr class="section-divider">', unsafe_allow_html=True)
    section_header("Data-type badges")
    st.markdown("""
| Badge | Meaning |
|-------|---------|
| **Historical** | Derived directly from observed trip data |
| **Estimated** | Calculated from trip data + public pricing assumptions |
| **Forecast** | Generated by the XGBoost demand model |
| **Scenario** | User-configured what-if simulation |
| **External Evidence** | Case studies from other cities (not benchmarked against NYC) |
    """)

    # ── Limitations ──
    st.markdown('<hr class="section-divider">', unsafe_allow_html=True)
    section_header("Known limitations")
    st.markdown("""
- **Revenue figures are estimates**, not audited financials. Based on public pricing and trip volume.
- **Station capacity** is self-reported dock count — actual available bikes/docks may differ.
- **MTA data** reflects aggregated ridership and reliability signals, not individual station-level metrics.
- **Weather features** use deviation from monthly climate normals, not raw values.
- **Forecast model** was trained on NYC data only. Transfer to other cities requires retraining.
- **Public benefit estimates** (health, congestion, emissions) use literature-based per-trip values.
    """)
